### ISSUE TITLE
[qa] Mention that openwisp-utils-qa-checks has been renamed to openwisp-qa-check

### ISSUE THREAD

**Issue by PabloCastellano** [openwisp/openwisp2-docs#104]
See https://github.com/openwisp/openwisp-utils/issues/94 for more information

**Comment by nemesisdesign** [comment]
To be done once openwisp-utils 0.5.0 is released.

**Comment by nemesisdesign** [comment]
Closed by e05f1201cda35b19b96a681cbf4d30f282849e58
