### ISSUE TITLE
[qa] Add run-qa-check script

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#111]
Add run-qa-check script, make sure it includes the 404 link check we have in openwisp-website and openwisp-radius, eg: https://github.com/openwisp/openwisp-radius/blob/master/run-qa-checks#L10-L16

**Comment by morrme** [comment]
@nemesisdesign  For this one, I'm assuming you also want the openwisp-utils version bumped up to 0.5.1 ? 

Should the 404 check be in a conditional statement as in `[openwisp-radius](https://github.com/openwisp/openwisp-radius/blob/master/run-qa-checks#L10-L16)`, or without it as with `[openwisp-website](https://github.com/openwisp/OpenWISP-Website/blob/ceb048b6103c5b35f65c2d943a7266a38fe6747b/run-qa-checks#L8-L12)` ?

**Comment by devkapilbansal** [comment]
@nemesisdesign I will work on this issue
