### ISSUE TITLE
[docs] Python style conventions are outdated

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#122]
We do not use `runflake8` and `runisort` scripts anymore, we now use `./run-qa-checks`.

This section should be updated: https://openwisp.io/docs/developer/contributing.html#coding-style-conventions

**Comment by FahadAminShovon** [comment]
is the ``./run-qa-checks`` launching ``flake8`` and ``issort`` ??

**Comment by pandafy** [comment]
> is the ./run-qa-checks launching flake8 and issort ??

Yes. You can look at [`run-qa-checks` script in this repository](https://github.com/openwisp/openwisp2-docs/blob/master/run-qa-checks) to learn more.

**Comment by prajwal296** [comment]
I want to work on this

**Comment by devkapilbansal** [comment]
@prajwal296 just go ahead

**Comment by Purhan** [comment]
I hope this is closed in https://github.com/openwisp/openwisp2-docs/commit/2f7cef6e5cf629f485379952b34106b864e022b7
Please reopen if not

**Comment by nemesisdesign** [comment]
Thanks @Purhan, you're right, I forgot we had an issue.
