### ISSUE TITLE
Define the values and goals of the OpenWISP community

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#15]
I will add the following sections in the near future:

- What are the values which the founders had when they created OpenWISP?
- What other values were brought in by further contributors?
- Where is the community heading to?

**Comment by HargovindArora** [comment]
@nemesisdesign I'm working on this. Please specify in which file I have to do this or I should create a new one?

**Comment by xamfy** [comment]
@HargovindArora yes, add a new file with an appropriate name

**Comment by HargovindArora** [comment]
@xamfy I'm working on this
:)

**Comment by xamfy** [comment]
@HargovindArora How's it going?
