### ISSUE TITLE
[CI] Build failed on `Setup google cloud`

### ISSUE THREAD

**Issue by Aryamanz29** [openwisp/openwisp2-docs#151]
- When PR is raised for `master` branch, Current `CI build` failed with errors given below 👇, We need to investigate why this is happening 🤔

**NOTE :** This step should only be executed after PR is being merged.

**PR :**  https://github.com/openwisp/openwisp2-docs/pull/150

**FAILED BUILD :**  https://github.com/openwisp/openwisp2-docs/runs/5114910806?check_suite_focus=true

```bash
Warning: google-github-actions/setup-gcloud is pinned at "master". We strongly advise against pinning to "@master" as it may be unstable. Please update your GitHub Action YAML from:

    uses: 'google-github-actions/setup-gcloud@master'

to:

    uses: 'google-github-actions/setup-gcloud@v0'

Alternatively, you can pin to any git tag or git SHA in the repository.
/usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/6d3ecbef-f8a6-42df-b157-14a940b954cb -f /home/runner/work/_temp/b2d6b04f-dd01-4a7a-9d42-60cc30693e[13](https://github.com/openwisp/openwisp2-docs/runs/5114910806?check_suite_focus=true#step:7:13)
No credentials detected, skipping authentication
Error: google-github-actions/setup-gcloud failed with: no credentials provided to export
```

**Comment by pandafy** [comment]
Thanks for creating this issue @Aryamanz29. The CI tries to upload the generated website on PRs as well. We should  break the `build` job into two parts - one for running QA checks and other for uploading it to google cloud.

We can even break it into two different workflows if required.

**Comment by ashutosh887** [comment]
Please assign this Issue to me @pandafy @Aryamanz29

**Comment by Aryamanz29** [comment]
@pandafy Please look into this 😄

**Comment by pandafy** [comment]
@ashutosh887 you don't need to wait for assignment. You can start working on this.

**Comment by ashutosh887** [comment]
Sure
