### ISSUE TITLE
Add a presentation collection page

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#16]
Add a page in which we collect presentations that talk about OpenWISP 2, different languages are allowed, each language will have its own section.

**Comment by xamfy** [comment]
Will it contain both talks and slides?

**Comment by nemesisdesign** [comment]
@xamfy yes I think it would be useful to have both if possible

**Comment by nemesisdesign** [comment]
Merged issue content with https://github.com/openwisp/openwisp2-docs/issues/17.
