### ISSUE TITLE
Openwisp docs link to github instead of openwisp

### ISSUE THREAD

**Issue by Darin755** [openwisp/openwisp2-docs#181]
I noticed that all of the links inside of the docs point towards github instead of openwisp. I don't know if that was intentional but this seems to be problematic as github fails to render them due to size.

Would it be possible to switch them to the openwisp website instead? I don't mind working on a PR but I'm not familiar with openwisp or its docs.

**Comment by nemesifier** [comment]
We do not have the entire documentation of each module in this repository, we need to come up with a solution for that.
In the meantime we were linking the README of each module, but unfortunately a recent Github update seems to have broken this mechanism.

**Comment by nemesifier** [comment]
We are actively working on #107 to solve this. Let's continue the discussion there.

**Comment by Darin755** [comment]
Thanks
