### ISSUE TITLE
Fix duplication of "Technologies" and "Glossary"

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#23]
@xamfy, @HargovindArora right now we have two pages that seem redundant, we need to merge them.

Glossary has a nice structure and we should keep it that way, we could add some of the content in "Technologies Involved" which is missing from "Glossary", then I'm not sure which of the two titles is better, I really don't have a clear idea now, but for the moment we can focus on merging the contents, can you do this?

**Comment by HargovindArora** [comment]
@nemesisdesign Sure, I was thinking the same that we were duplicating the stuff! I was thinking to keep the title as 'Technologies Involved', because then people will know, come and read about technologies and word 'Glossary' might sound vague! Rest is your opinion! What do you say? :D

**Comment by xamfy** [comment]
@nemesisdesign @HargovindArora I agree, but the problem is we can't keep general terms in technologies, right?

**Comment by nemesisdesign** [comment]
We can rename the merged page to "Technologies and Architectures used".
