### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#24]
We need a simple code of conduct which clearly states that any type of racial, religious or sexual harassment as well as ad-hominem attack is not tolerated in our community.

A good example is https://www.djangounderthehood.com/coc/ although we need something simpler.

We clearly need to state that anyone who will breach these rules will be kindly asked to leave the community or forcibly removed if they continues in assuming behaviour that goes against our values.

**Comment by adityac8** [comment]
Hey @nemesisdesign I would like to work on this 🙂

**Comment by adityac8** [comment]
Hey @nemesisdesign @BrainBuzzer I have created the code of conduct. I wanted to know, where should I put it in the repo so that I can create a PR.  Also, I have seen that the files are in `rst` format. Should the Code of Conduct also be in `rst` or `MD`?

**Comment by adityac8** [comment]
Hello, @anurag-ks @nemesisdesign  I added the code of conduct with the mentioned changes.
Kindly review :)

**Comment by nemesisdesign** [comment]
Thanks @adityac8
