### ISSUE TITLE
Add travis build which checks the docs

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#28]
Just like we do in django-freeradius see:

- [django-freeradius/.travis.yml](https://github.com/openwisp/django-freeradius/blob/master/.travis.yml#L31)
- [django-freeradius/runsphinx-build](https://github.com/openwisp/django-freeradius/blob/master/runsphinx-build)

**Comment by anurag-ks** [comment]
Working on it.

**Comment by anurag-ks** [comment]
@nemesisdesign the repo owner should enable travis-ci build on this repo ?

**Comment by nemesisdesign** [comment]
@anurag-ks here it is: https://travis-ci.org/openwisp/openwisp2-docs
