### ISSUE TITLE
Enforce maximum line length in the docs

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#29]
We should enforce the maximum line length of each rst file to 75 characters because this makes editing multiple files in split editor mode or in split terminal vim windows much easier which in turns increases productivity.

I have no idea yet how to do this, I hope there's some tool available that does it.

Once this is done, it should be added to the [travis build mentioned in issue 28](https://github.com/openwisp/openwisp2-docs/issues/28).

**Comment by HizkiFW** [comment]
I made [a small tool](https://github.com/HizkiFW/newline-inator) to do this for text files (and maybe code too) but I'm not sure if it'll work on reStructuredText, since (afaik) indentation matters. I might make it a bit smarter soon.

**Comment by nemesisdesign** [comment]
@HizkiFW have you tried this? https://docs.python.org/3/library/textwrap.html

**Comment by HizkiFW** [comment]
Oh wow, I did not realize that thing exists. That makes things much simpler.
