### ISSUE TITLE
About HTML

### ISSUE THREAD

**Issue by MiHiR151203** [openwisp/openwisp2-docs#42]
After Doing Everything, At Last Step To Make HTML It Shows That, bash: make: command not found
Any Fix. What Should I Do

**Comment by nemesisdesign** [comment]
I think you need to install make, come on our chat to ask this type of questions, we use this system for bug tracking

**Comment by MiHiR151203** [comment]
Sir I Have A Question That There Are 10 Docs Available, So How Many Docs Should I Open And Send Screenshot.. Please Reply..

**Comment by nemesisdesign** [comment]
Ask these questions in our chat: https://gitter.im/openwisp/general
