### ISSUE TITLE
Explain how to use support channels

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#47]
I've been repeating this too many times now:

> If you need help in solving problems, using the chat is better, but if you want to discuss important implementation details or ask detailed questions regarding a specific openwisp module or feature using the mailing list is better for several reasons, but the best reason is that all discussions are indexed on search engines and easily retrievable in the future, so the mailing list over time become some kind of fall-back documentation archive which is very good for any open source project.

We need to find a good place in the docs to explain this.

**Comment by rohithasrk** [comment]
Developer guidelines is the best place maybe. Or mention it in the contact us page.

**Comment by adityac8** [comment]
As the user has to contact regarding his **contributions**, I suggest we can add that to the `developer/contibuting` page. What do you think @nemesisdesign @rohithasrk ?

**Comment by nemesisdesign** [comment]
I added this info here a while ago and it's working quite well because the majority of new mailing list subscribers are setting their subscription to receive emails, which was not happening before: http://openwisp.io/docs/general/help-us.html#write-to-the-mailing-list
I'm satisfied of the result so I will close this issue.
