### ISSUE TITLE
[coding] Style conventions

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#48]
we need a style convention section in which we describe our coding style conventions:

- commit message style (this is explained in the contributing guidelines but the section is not titled properly and I guess not many people are reading it)
- python code convention
- javascript code convention
- openwrt related code convention

**Comment by HargovindArora** [comment]
@nemesisdesign I'm on this!

**Comment by HargovindArora** [comment]
@nemesisdesign Hey, I am busy with my exams and lots of other stuff so I am not able to do this! I'll report once it all over!

**Comment by nemesisdesign** [comment]
Thanks @HargovindArora!
