### ISSUE TITLE
Remove mention of LEDE

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#56]
LEDE has been merged back in OpenWRT, we can update the docs and remove any mention to it.

*Note*: the configure-device.rst page needs to be updated accordingly, including the download URLs.

**Comment by kira0204** [comment]
Let's move this to `To do (documentation)`?

**Comment by nemesisdesign** [comment]
@kira0204 what do you mean?

**Comment by kira0204** [comment]
I meant should we move this to `To do (documentation)` under Kanban board?

**Comment by nemesisdesign** [comment]
yes definitely, let me do that
