### ISSUE TITLE
[Configuration] Explain how to use configuration variables

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#57]
**Reserved for GCI**

Explain how to use configuration variables and the default device context variables described here: https://github.com/openwisp/django-netjsonconfig#netjsonconfig_context

Please ensure to have dedicated time understood

**Comment by pawelplsi** [comment]
Hello, it's my GCI task. I have read something about the context variables and I think I've understood what is it about, but I don't really know what's the point of this issue, it's really well explained how do these variables work [there](http://netjsonconfig.openwisp.org/en/latest/general/basics.html#context-configuration-variables), should I improve this doc somehow, or should I write something like a tutorial? Could you point me a little?

**Comment by nemesisdesign** [comment]
@pawelplsi the section at `http://netjsonconfig.openwisp.org/en/latest/general/basics.html#context-configuration-variables` explains the configuration variable from the point of view of a developer using the library netjsonconfig.

We must now help non developers who are using OpenWISP to understand how to use these variables via the OpenWISP UI.

**Comment by pawelplsi** [comment]
Okay, thanks :smile:
