### ISSUE TITLE
[docs] Some possible improvements

### ISSUE THREAD

**Issue by EdgeKing810** [openwisp/openwisp2-docs#62]
So I had a task where I had to a vm with OpenWRT and connect it to OpenWISP locally. There were some challenges that I faced and here's a list of what can be improved so that other students/people don't get confused and know exactly what to do.

1.) I couldn't get the network to work in my OpenWRT vm. 
refer to: https://openwrt.org/docs/guide-user/virtualization/virtualbox-vm
For the second adapter, it wasn't mention what to use. I was using the PCInet-III or something instead of the Intel Pro (82540EM)
I thought it would be good to let you know so that future individuals don't face this problem.

2.) Oh and for the allocation of <ipaddr>, it would be better that on this tutorial if it was set to 192.168.56.3 (more than 192.168.56.2 as it is used for the OpenWISP Server).

3.) After setting up everything, I found out that no devices were being created on the local OpenWISP website.
I had the message "openwisp: OpenWISP config agent started" but there was nothing on the website.
I later found out (thanks to reza) how to fix all that. Some info on: http://openwisp.io/docs/user/configure-device.html need to be improved as there is some confusion. Firstly lines "option uuid" and "option key" should be commented I think, secondly it would be great if it was mentionned that if we had our OpenWISP server locally (e.g 192.168.56.2), then the "option url" would be 'https://192.168.56.2'. That is more beginner-friendly as they know what to write, if <https> should be mentioned and if whether ".../admin" should be written or not.

Otherwise everything is great! I am not saying that anything was bad. On the contrary, the tutorial is really awesome! I am just suggesting how it would better, that's all!

**Comment by atb00ker** [comment]
>  Firstly lines "option uuid" and "option key" should be commented I think

I only need to confirm this line, the rest looks good to me! :+1:
