### ISSUE TITLE
[docs] Document template tags

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#63]
Document how to use the template tag feature.

**Comment by vickywane** [comment]
is this with particular reference to django ?

**Comment by atb00ker** [comment]
It's in reference to the tags that you can set for a template. Go to `/admin/config/template/add/` to see more. :smile:

**Comment by nemesisdesign** [comment]
@vickywane it's an openwisp feature, it's the tag field of the `Template` model, look on the mailing list archive and you should find something I wrote back then

**Comment by vickywane** [comment]
I'll go read through it...  Merci à touś

**Comment by TheOneAboveAllTitan** [comment]
@nemesisdesign were you referring to this? https://groups.google.com/d/msg/openwisp/vdQekq8UrBE/wkrhbNKNAgAJ

**Comment by atb00ker** [comment]
In this task:
1. You have to try out tags by using one. Take a screenshot of the same.
2. Document the "How to use tags feature" in our documentation.

You may find the following useful to document:
- https://github.com/openwisp/django-netjsonconfig/issues/48
- https://groups.google.com/d/msg/openwisp/vdQekq8UrBE/wkrhbNKNAgAJ

**Comment by nemesisdesign** [comment]
This issue is still up for anyone that wants to help out with it.

**Comment by vickywane** [comment]
I would have a look at the associated resources and try write the docs.

However anyone else interested is free to work on this .
