### ISSUE TITLE
[docs] Document basic template usage

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#64]
Create a new page in the user documentation that explains the following:

- what is a configuration template
- mention (and link) [NetJSON](http://netjson.org) and [netjsonconfig](http://netjsonconfig.openwisp.org/)
- provide at least 3 example templates for OpenWRT, you can take some from the [netjsonconfig documentation](http://netjsonconfig.openwisp.org/en/latest/backends/openwrt.html)
- add a link to this new page at the end of the [configure-device.rst](https://github.com/openwisp/openwisp2-docs/blob/master/user/configure-device.rst) to make it easier for users to find it
- don't forget to add the page to the main index so it will be listed in the main menu of the documentation website

**Comment by EdgeKing810** [comment]
May I take this? :/
