### ISSUE TITLE
[mesh] Tutorial on mesh networking

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp2-docs#65]
It would be great to have a tutorial that explains how to:

- setup a configuration template that creates a mesh network with 802.11s and OLSRd2
- mention encryption if needed
- explain how to configure the network topology module to collect the topology information using the RECEIVE strategy, it's documented in Italian here: http://wiki.ninux.org/TopologyVisualizer (the script can be installed on the device with an additional template)
- explain how to see the network topology graph
- mention daily historic data is collected and can be viewed 

In the future we could have more variants for 802.11s and Batman-adv, 802.11s and Babel, 802.11s and BMX7.

**Comment by pacicap** [comment]
please may i work on this ?i am interested in solving this issue . i am new to documentation please may i have a guide on how to get started?

**Comment by atb00ker** [comment]
Hi @pacicap , yes, please feel free to work on it.
If you are looking for general help. please checkout the README of the repository.
You can also ask for help on the Gitter channel or mailing list. :smile:

**Comment by pacicap** [comment]
Ok thanks

**Comment by junewinter2013** [comment]
Hi @pacicap,

I am looking at setting up a mesh network with openwisp, have you progressed much with the documentation ?

I realised that it has been a long time (almost 4 years), but in case you have started the documentation already, I am happy to continuing with it, updating the doc as I learn how to set mesh networking up.

Thanks,
June

**Comment by pacicap** [comment]
Hello,

Sorry I haven't started with the documentation. I just worked on the issue
and solved it.

Kind regards,
Pacilia

**Comment by nemesifier** [comment]
Closed by https://github.com/openwisp/openwisp2-docs/pull/182.
