### ISSUE TITLE
[docs] Python resource link is dead

### ISSUE THREAD

**Issue by ankit-kumar-dwivedi** [openwisp/openwisp2-docs#79]
The mentioned python(book) [resource link](http://www.diveintopython3.net/) under `Programming languages and frameworks:` is dead and need to be replaced.

**Comment by atb00ker** [comment]
File: https://github.com/openwisp/openwisp2-docs/blob/master/developer/google-summer-of-code.rst#time-to-start-hacking

I think the link can be changed to either:
- https://www.learnpython.org/
or 
- http://interactivepython.org/runestone/static/pythonds/index.html

**Comment by nemesisdesign** [comment]
Please send a patch if you can

**Comment by ankit-kumar-dwivedi** [comment]
I will send a PR for this one @namesisdesign :)
