### ISSUE TITLE
Add a README and requirements.txt

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#8]
@HargovindArora we need to have something like this:

- https://github.com/battlemesh/battlemesh-test-docs/blob/master/README.rst
- https://github.com/battlemesh/battlemesh-test-docs/blob/master/requirements.txt

**Comment by HargovindArora** [comment]
@nemesisdesign Sure I'll work on this :+1:

**Comment by nemesisdesign** [comment]
thx @HargovindArora
