### ISSUE TITLE
[GCI] Update page of GCI to 2019

### ISSUE THREAD

**Issue by OfficialHacks** [openwisp/openwisp2-docs#89]

**Comment by IAmAMissingColon** [comment]
Hello @OfficialHacks , You can make a simple PR without opening an issue :smile:

**Comment by EdgeKing810** [comment]
He's probably trying to respect the commit message guidelines :smiley: @IAmAMissingColon 
So, he'll specify his PR will close this issue.

**Comment by IAmAMissingColon** [comment]
> He's probably trying to respect the commit message guidelines  @IAmAMissingColon
> So, he'll specify his PR will close this issue.

Never Mind :smile:

**Comment by 2stacks** [comment]
Its already being addressed in https://github.com/openwisp/openwisp2-docs/pull/88.

**Comment by EdgeKing810** [comment]
@2stacks Ah, didn't notice that. @atb00ker proposed to do this specifically to get a student familiarized with doing PRs and following the commit message guidelines.

**Comment by 2stacks** [comment]
Ah, I see that now.  :speak_no_evil:
