### ISSUE TITLE
[docs] Add hint to use check-commit and openwisp-qa-format

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp2-docs#99]
We're adding `openwisp-qa-format` and a way to force the commit message check in https://github.com/openwisp/openwisp-utils/pull/89, we should update the docs to mention these two tools and suggest their usage.

**Comment by PabloCastellano** [comment]
I have sent a PR that mentions black and the new openwisp-qa-format script

I haven't explained a way to force the commit message check, will do it in https://github.com/openwisp/openwisp2-docs/issues/100
